---
- hosts: vm1
  become: true
  tasks:
    - name: Update all packages in Debian-based machines
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Install dependencies"
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-setuptools
          - python3-pip
          - libpq-dev
          - python-psycopg2
          - python3-django
          - htop
          - sysstat
          - atop
          - vim
          - wget
          - rsync
          - netcat
          - pwgen
          - jq
        state: present
